config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount GoodJob::Engine => "good-job"

  resources :reports, only: %i[index new create] do
    resources :detections, only: %i[index] do
      patch :resolve

      resources :call_stacks, only: %i[index] do
        patch :resolve

        resources :queries, only: %i[index]
      end
    end
  end

  # Defines the root path route ("/")
  root to: "reports#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def human_errors = errors.full_messages.join(", ")
end

app/models/call_stack.rb
# frozen_string_literal: true

class CallStack < ApplicationRecord
  belongs_to :detection

  has_many :queries, dependent: :destroy

  validates :md5, presence: true, uniqueness: { scoped: :detection }
  validates :subroutines, presence: true

  scope :unresolved, -> { where(resolved: false) }
end

app/models/detection.rb
# frozen_string_literal: true

class Detection < ApplicationRecord
  belongs_to :report

  has_many :call_stacks, dependent: :destroy
  has_many :queries, through: :call_stacks

  validates :caller, presence: true, uniqueness: { scoped: :report }

  scope :unresolved, -> { where(resolved: false) }

  def resolve_in_cascade
    ActiveRecord::Base.transaction do
      return true if update(resolved: true) && call_stacks.unresolved.update_all(resolved: true)

      raise ActiveRecord::Rollback
    end

    false
  end
end

app/models/query.rb
# frozen_string_literal: true

class Query < ApplicationRecord
  belongs_to :call_stack

  validates :md5, presence: true, uniqueness: { scoped: :call_stack }
  validates :optimizable_list, presence: true
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  has_many :detections, dependent: :destroy

  has_one_attached :zipped_report

  validates :name, presence: true, uniqueness: { scoped: :uri }
  validates :uri, presence: true, format: { with: URI::DEFAULT_PARSER.make_regexp }

  # TODO
  #
  # Performances could be improved by using something like 'insert_all' or 'activerecord-import'
  # (Yeah, it's ugly, but at least works, and looks functional!)
  def store_detection(logs_block)
    ActiveRecord::Base.transaction do
      detections
        .find_or_create_by!(caller: logs_block.caller)
        .call_stacks
        .create_with(subroutines: logs_block.call_stack)
        .find_or_create_by!(md5: logs_block.call_stack_md5)
        .queries
        .create_with(optimizable_list: logs_block.queries)
        .find_or_create_by!(md5: logs_block.queries_md5)
    rescue ActiveRecord::RecordInvalid => e
      Rails.logger.error "#{e.class}: #{e.message}"
      raise ActiveRecord::Rollback
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/call_stacks_controller.rb
# frozen_string_literal: true

class CallStacksController < ApplicationController
  before_action :set_report
  before_action :set_detection
  before_action :set_call_stack, only: :resolve

  def index
    @pagy, @call_stacks = pagy(@detection.call_stacks)
  end

  def resolve
    respond_to do |format|
      if @call_stack.update(resolved: true)
        format.html do
          redirect_to report_detection_call_stacks_path,
                      notice: "Call stack #{@call_stack.id} was resolved."
        end
      else
        flash.now.alert = @call_stack.human_errors
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_report
      @report = Report.find(params[:report_id])
    end

    def set_detection
      @detection = @report.detections.find(params[:detection_id])
    end

    def set_call_stack
      @call_stack = @detection.call_stacks.find(params[:call_stack_id])
    end
end

app/controllers/detections_controller.rb
# frozen_string_literal: true

class DetectionsController < ApplicationController
  before_action :set_report
  before_action :set_detection, only: :resolve

  def index
    detections = @report.detections
    detections = detections.where("caller LIKE ?", "%#{query}%") if query

    @pagy, @detections = pagy(detections)
  end

  def resolve
    respond_to do |format|
      if @detection.resolve_in_cascade
        format.html do
          redirect_to report_detections_path,
                      notice: "Detection #{@detection.id} was resolved."
        end
      else
        flash.now.alert = @detection.human_errors
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_report
      @report = Report.find(params[:report_id])
    end

    def set_detection
      @detection = @report.detections.find(params[:detection_id])
    end

    def query
      params[:q]&.downcase
    end
end

app/controllers/queries_controller.rb
# frozen_string_literal: true

class QueriesController < ApplicationController
  before_action :set_report, only: :index
  before_action :set_detection, only: :index
  before_action :set_call_stack, only: :index

  def index
    @pagy, @queries = pagy(@call_stack.queries)
  end

  private

    def set_report
      @report = Report.find(params[:report_id])
    end

    def set_detection
      @detection = @report.detections.find(params[:detection_id])
    end

    def set_call_stack
      @call_stack = @detection.call_stacks.find(params[:call_stack_id])
    end
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  def index
    @pagy, @reports = pagy(Report.all.order(id: :desc))
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        ProcessReportJob.perform_later(@report)
        format.html { redirect_to reports_path, notice: "Report was successfully created." }
      else
        flash.now.alert = @report.human_errors
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

    def report_params
      params.require(:report).permit(:name, :uri)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/detections_helper.rb
module DetectionsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/call_stacks/index.html.erb
<section class="container pt-12 mx-auto">
  <h1 class="text-2xl font-medium text-gray-800 dark:text-white">Call stacks</h1>
  <p class="text-xs dark:text-white">The list of call stacks having the same caller but different subroutines</p>

  <%= render "layouts/breadcrumbs", breadcrumbs: [{ text: "Reports", path: reports_path }, { text: "Detections", path: report_detections_path }] %>

  <% @call_stacks.find_each do |call_stack| %>
    <div class="mt-6 sm:flex sm:items-center sm:justify-between">
      <h3 class="text-base text-gray-800 dark:text-white">Call stack ID <%= call_stack.id %> <span class="text-xs">(<%= l call_stack.created_at, format: :long %>)</span></h1>

      <div class="flex items-center gap-x-3">
        <% if call_stack.resolved? %>
          <span class="w-1/2 px-5 py-2 text-sm text-white transition-colors duration-200 bg-green-500 border rounded-lg sm:w-auto dark:hover:bg-green-800 hover:bg-green-400">
            Resolved
          </span>
        <% else %>
          <%= form_with method: :patch, url: report_detection_call_stack_resolve_path(call_stack.detection.report, call_stack.detection, call_stack) do |f| %>
            <%= f.submit "Resolve", class: "w-1/2 px-5 py-2 text-sm text-white transition-colors duration-200 bg-blue-500 border rounded-lg sm:w-auto hover:bg-blue-400 cursor-pointer" %>
          <% end %>
        <% end %>

        <%= link_to "Queries (#{call_stack.queries.count})",
                    report_detection_call_stack_queries_path(call_stack.detection.report, call_stack.detection, call_stack),
                    class: "w-1/2 px-5 py-2 text-sm text-gray-800 transition-colors duration-200 bg-white border rounded-lg sm:w-auto dark:hover:bg-gray-800 dark:bg-gray-900 hover:bg-gray-100 dark:text-white dark:border-gray-700" %>
      </div>
    </div>

    <div class="flex flex-col overflow-x-auto">
      <div class="inline-block min-w-full py-2 align-middle">
        <div class="overflow-x-auto border border-gray-200 dark:border-gray-700 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead class="bg-gray-50 dark:bg-gray-800">
              <tr>
                <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Subroutines</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900">
              <% call_stack.subroutines.each do |subroutine| %>
                <tr>
                  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
                    <div class="inline px-3 py-1 text-sm font-normal rounded-full text-emerald-500 gap-x-2 bg-emerald-100/60 dark:bg-gray-800">
                      <%= subroutine %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/detections/index.html.erb
<section class="container pt-12 mx-auto">
  <h1 class="text-2xl font-medium text-gray-800 dark:text-white">Detections</h1>
  <p class="text-xs dark:text-white">A detection is identified by the caller, hence the first subroutine in the call stack</p>

  <%= render "layouts/breadcrumbs", breadcrumbs: [{ text: "Reports", path: reports_path }] %>

  <section class="relative w-full max-w-md rounded-md mt-12">
    <h3 class="text-lg font-medium">Search among the detections</h3>

    <%= form_with url: report_detections_path, method: :get do |f| %>
      <div class="relative mt-2">
        <span class="absolute inset-y-0 left-0 flex items-center pl-3">
          <svg class="w-5 h-5 text-gray-400" viewBox="0 0 24 24" fill="none">
            <path d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
          </svg>
        </span>

        <%= f.text_field :q, value: params[:q], placeholder: "Search by caller", class: "w-full py-3 pl-10 pr-4 text-gray-700 bg-white border rounded-md dark:bg-gray-900 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 dark:focus:border-blue-300 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40" %>
      </div>
    <% end %>
  </section>

  <div class="flex flex-col mt-6 overflow-x-auto">
    <div class="inline-block min-w-full py-2 align-middle">
      <div class="overflow-x-auto border border-gray-200 dark:border-gray-700 md:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead class="bg-gray-50 dark:bg-gray-800">
            <tr>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">ID</th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Caller</th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Actions</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900">
            <% @detections.find_each do |detection| %>
              <tr>
                <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
                  <h2 class="font-medium text-gray-800 dark:text-white"><%= detection.id %></h2>
                </td>
                <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
                  <div class="inline px-3 py-1 text-sm font-normal rounded-full text-emerald-500 gap-x-2 bg-emerald-100/60 dark:bg-gray-800">
                    <%= detection.caller %>
                  </div>
                  <h4 class="text-xs text-gray-700 dark:text-gray-200 mt-2"><%= l detection.created_at, format: :long %></h4>
                </td>
                <td class="px-4 py-4 text-sm whitespace-nowrap">
                  <div class="flex items-center gap-x-3">
                    <% if detection.resolved? %>
                      <span class="w-1/2 px-5 py-2 text-sm text-white transition-colors duration-200 bg-green-500 border rounded-lg sm:w-auto dark:hover:bg-green-800 hover:bg-green-400">
                        Resolved
                      </span>
                    <% else %>
                      <%= form_with method: :patch, url: report_detection_resolve_path(detection.report, detection) do |f| %>
                        <%= f.submit "Resolve", class: "w-1/2 px-5 py-2 text-sm text-white transition-colors duration-200 bg-blue-500 border rounded-lg sm:w-auto hover:bg-blue-400 cursor-pointer" %>
                      <% end %>
                    <% end %>

                    <%= link_to "Call stacks (#{detection.call_stacks.unresolved.count})",
                                report_detection_call_stacks_path(detection.report, detection),
                                class: "w-1/2 px-5 py-2 text-sm text-gray-800 transition-colors duration-200 bg-white border rounded-lg sm:w-auto dark:hover:bg-gray-800 dark:bg-gray-900 hover:bg-gray-100 dark:text-white dark:border-gray-700" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_breadcrumbs.html.erb
<div class="flex items-center overflow-x-auto whitespace-nowrap mt-6">
  <%= link_to root_path, class: "text-gray-600 dark:text-gray-200 hover:underline" do %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" data-slot="icon" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m2.25 12 8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
    </svg>
  <% end %>

  <% breadcrumbs.each do |breadcrumb| %>
    <span class="mx-2 text-gray-500 dark:text-gray-300">/</span>
    <%= link_to breadcrumb[:text], breadcrumb[:path], class: "text-gray-600 dark:text-gray-200 hover:underline" %>
  <% end %>
</div>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <section class="container pt-12 mx-auto">
    <section class="mx-auto">
      <% flash.each do |type, msg| %>
        <% case type %>
        <% when "alert" %>
          <div class="flex w-full max-w-sm overflow-hidden bg-white rounded-lg shadow-md dark:bg-gray-800">
            <div class="flex items-center justify-center w-12 bg-red-500">
              <svg class="w-6 h-6 text-white fill-current" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <path d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z" />
              </svg>
            </div>

            <div class="px-4 py-2 -mx-3">
              <div class="mx-3">
                <span class="font-semibold text-red-500 dark:text-red-400">Error</span>
                <p class="text-sm text-gray-600 dark:text-gray-200"><%= msg %></p>
              </div>
            </div>
          </div>
        <% when "notice" %>
          <div class="flex w-full max-w-sm overflow-hidden bg-white rounded-lg shadow-md dark:bg-gray-800">
            <div class="flex items-center justify-center w-12 bg-blue-500">
              <svg class="w-6 h-6 text-white fill-current" viewBox="0 0 40 40" xmlns="http://www.w3.org/2000/svg">
                <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM21.6667 28.3333H18.3334V25H21.6667V28.3333ZM21.6667 21.6666H18.3334V11.6666H21.6667V21.6666Z" />
              </svg>
            </div>

            <div class="px-4 py-2 -mx-3">
              <div class="mx-3">
                <span class="font-semibold text-blue-500 dark:text-blue-400">Info</span>
                <p class="text-sm text-gray-600 dark:text-gray-200"><%= msg %></p>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </section>
  </section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ProsopiteUi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="dark:bg-gray-900	">
    <main>
      <%= render "layouts/flash" %>

      <%= yield %>

      <% if defined?(@pagy) && @pagy.pages > 1 %>
        <section class="container mx-auto my-6">
          <div class="flex items-center justify-between">
            <%== pagy_nav(@pagy) %>
          </div>
        </section>
      <% end %>
    </main>
  </body>
</html>

app/views/queries/index.html.erb
<section class="container pt-12 mx-auto">
  <h1 class="text-2xl font-medium text-gray-800 dark:text-white">Queries</h1>
  <p class="text-xs dark:text-white">The N+1 queries executed by a given call stack</p>

  <%= render "layouts/breadcrumbs", breadcrumbs: [{ text: "Reports", path: reports_path }, { text: "Detections", path: report_detections_path }, { text: "Call stacks", path: report_detection_call_stacks_path }] %>

  <% @queries.find_each do |query| %>
    <div class="mt-6 sm:flex sm:items-center sm:justify-between">
      <h3 class="text-base text-gray-800 dark:text-white">Query ID <%= query.id %></h3>
    </div>

    <div class="flex flex-col overflow-x-auto">
      <div class="inline-block min-w-full py-2 align-middle">
        <div class="overflow-x-auto border border-gray-200 dark:border-gray-700 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
            <thead class="bg-gray-50 dark:bg-gray-800">
              <tr>
                <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Queries</th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900">
              <% query.optimizable_list.each do |optimizable_list_item| %>
                <tr>
                  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
                    <div class="inline px-3 py-1 text-sm font-normal rounded-full text-emerald-500 gap-x-2 bg-emerald-100/60 dark:bg-gray-800">
                      <%= optimizable_list_item %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</section>

app/views/reports/index.html.erb
<section class="container pt-12 mx-auto">
  <div class="sm:flex sm:items-center sm:justify-between">
    <h1 class="text-2xl font-medium text-gray-800 dark:text-white">Reports</h1>

    <div class="flex items-center gap-x-3">
      <%= link_to "Jobs", "/good-job", class: "w-1/2 px-5 py-2 text-sm text-gray-800 transition-colors duration-200 bg-white border rounded-lg sm:w-auto dark:hover:bg-gray-800 dark:bg-gray-900 hover:bg-gray-100 dark:text-white dark:border-gray-700" %>
      <%= link_to "New Report", new_report_path, class: "w-1/2 px-5 py-2 text-sm text-white transition-colors duration-200 bg-blue-500 border rounded-lg sm:w-auto hover:bg-blue-400" %>
    </div>
  </div>

  <%= render "layouts/breadcrumbs", breadcrumbs: [] %>

  <div class="flex flex-col mt-6 overflow-x-auto">
    <div class="inline-block min-w-full py-2 align-middle">
      <div class="overflow-x-auto border border-gray-200 dark:border-gray-700 md:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
          <thead class="bg-gray-50 dark:bg-gray-800">
            <tr>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">ID</th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Name</th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">URI</th>
              <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500 dark:text-gray-400">Actions</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900">
            <% @reports.find_each do |report| %>
              <tr>
                <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
                  <h2 class="font-medium text-gray-800 dark:text-white"><%= report.id %></h2>
                </td>
                <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
                  <div class="inline px-3 py-1 text-sm font-normal rounded-full text-emerald-500 gap-x-2 bg-emerald-100/60 dark:bg-gray-800">
                    <%= report.name %>
                  </div>
                  <h4 class="text-xs text-gray-700 dark:text-gray-200 mt-2"><%= l report.created_at, format: :long %></h4>
                </td>
                <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
                  <div class="inline px-3 py-1 text-sm font-normal rounded-full text-emerald-500 gap-x-2 bg-emerald-100/60 dark:bg-gray-800">
                    <%= report.uri %>
                  </div>
                </td>
                <td class="px-4 py-4 text-sm whitespace-nowrap">
                  <button class="w-1/2 px-5 py-2 text-sm text-gray-800 transition-colors duration-200 bg-white border rounded-lg sm:w-auto dark:hover:bg-gray-800 dark:bg-gray-900 hover:bg-gray-100 dark:text-white dark:border-gray-700">
                    <%= link_to "Detections (#{report.detections.unresolved.count})", report_detections_path(report) %>
                  </button>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/reports/new.html.erb
<section class="container pt-12 mx-auto">
  <div class="flex items-center py-4 overflow-x-auto whitespace-nowrap">
    <%= link_to "Home", root_path, class: "text-gray-600 dark:text-gray-200 hover:underline" %>
  </div>

  <section class="p-6 mx-auto bg-white rounded-md shadow-md dark:bg-gray-800">
    <h2 class="text-lg font-semibold text-gray-700 capitalize dark:text-white">Create a new Report</h2>

    <%= form_for @report do |f| %>
      <div class="grid grid-cols-1 gap-6 mt-4 sm:grid-cols-1">
        <div>
          <%= f.label :name, "Friendly name", class: "text-gray-700 dark:text-gray-200" %>
          <%= f.text_field :name, class: "block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-200 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 focus:ring-blue-300 focus:ring-opacity-40 dark:focus:border-blue-300 focus:outline-none focus:ring" %>
        </div>
        <div>
          <%= f.label :uri, "Prosopite Zip URI", class: "text-gray-700 dark:text-gray-200" %>
          <%= f.text_field :uri, class: "block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-200 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 focus:ring-blue-300 focus:ring-opacity-40 dark:focus:border-blue-300 focus:outline-none focus:ring" %>
        </div>
        <div class="flex justify-end mt-6">
          <%= f.submit "Save", class: "px-8 py-2.5 leading-5 text-white transition-colors duration-300 transform bg-gray-700 rounded-md hover:bg-gray-600 focus:outline-none focus:bg-gray-600" %>
        </div>
      </div>
    <% end %>
  </section>
</section>